### ISSUE TITLE
drag and select only works on #container and not [viz] component body

### ISSUE THREAD

**Issue by sepans** [lenses/lenses-freeform#10]
@therewasaguy did you noticed that as soon as the mouse pointer enters the component body (when settings is open or in case of a viz component) while drag-and-selecting components, the selection gets interrupted. I don't know if there is a workaround for that....

**Comment by therewasaguy** [comment]
Hmm, I'm pretty sure this bug wasn't happening last week. I'll take a look.

**Comment by sepans** [comment]
Thanks @therewasaguy . no rush though. It is def a low priority issue

**Comment by therewasaguy** [comment]
Turns out this was introduced by my clones branch with this method, fixed it up!

https://github.com/lenses/lenses-freeform/commit/7b977c29d49f8872e3a17823c31919d5b3b2d859#diff-0a89681ee479ed43eb92dff866dee8a1R1061
